matrix:
  include:
    - os: linux
      env: CONDA_PYTHON_VERSION=3.6

    - os: linux
      env: CONDA_PYTHON_VERSION=3.7
 
     - os: linux
      env: CONDA_PYTHON_VERSION=3.8

    - os: osx
      env: CONDA_PYTHON_VERSION=3.6

    - os: osx
      env: CONDA_PYTHON_VERSION=3.7

    - os: osx
      env: CONDA_PYTHON_VERSION=3.8

before_install:
  - echo "Installing Miniconda environment..."
  - if [ $TRAVIS_OS_NAME == 'linux' ];
    then export MINICONDA_URL=https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh;
    else export MINICONDA_URL=https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh;
    fi
  - wget $MINICONDA_URL -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - source ~/miniconda/etc/profile.d/conda.sh # Initialize shell.
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -n questplus -c conda-forge python=$CONDA_PYTHON_VERSION pytest numpy scipy xarray json_tricks
  - conda activate questplus
  - conda list

install:
  - python setup.py build

  # Build & install sdist.
  - python setup.py sdist
  - pip install --no-deps dist/questplus-*.tar.gz
  - pip uninstall --yes questplus

  # Build & install wheel.
  - python setup.py bdist_wheel
  - pip install --no-deps dist/questplus-*.whl
  - pip uninstall --yes questplus

  - rm -rf dist/ build/

  - pip install .

script:
  - py.test
